### PR TITLE
Decomission website

### PR DESCRIPTION
**Pull request by torsava**
Data moved to wiki:
https://fedoraproject.org/wiki/SIGs/Python

### CODE REVIEW

**Comment by torsava** [comment]
@encukou If you have time for a sanity check, it'd be welcome. Otherwise I'll just merge.

**Comment by hroncok** [comment]
I can do the sanity check.

**Review by hroncok — APPROVED** [review]

**Comment by hroncok** [comment]
Merged. Is deploy automated?

**Comment by hroncok** [comment]
Yes it is.

**Pull request merged**
